### PR TITLE
Added code to clip out-of-dwi fiber coordinates

### PR DESCRIPTION
**Pull request by soichih**
Updated clipping code to handle fiber coordinates overflow (the previous patch only deals with underflow)

### CODE REVIEW

**Comment by francopestilli** [comment]
@soichih how do the results of the model (say weights and rmse), built with this new changes, compare to the results in the published paper? Have you tested that already?

**Comment by soichih** [comment]
@francopestilli I just ran a few more tests to compare the results and they are very close; within a usual stochastic margin. Once this PR is merged, I am planning to do more thorough testings before making a new release for app-life.

**Comment by soichih** [comment]
More comparison
1.7


master
master

29580 ABIDEII

**Comment by francopestilli** [comment]
@soichih ok let's try this merge we can revert if necessary.

**Comment by ccaiafa** [comment]
Hi @soichih, as I remember, with STN and HCP we haven't had any underflow or overflow problem. I remember that when I changed ceil to round, the new rmses were a little bit better (smaller).

**Pull request merged**
