### PR TITLE
feConnectomeSetDwi

### PR DESCRIPTION
**Pull request by rosemary-le**
fgGet should be fefgGet

### CODE REVIEW

**Comment by rosemary-le** [comment]
Add the 'fa' option to feGet (previously was only an option in fefgGet)

**Review by francopestilli — APPROVED** [review]

**Comment by francopestilli** [comment]
This seems good. It should not break other things. But it will generate slightly different results.

**Review by francopestilli — COMMENTED** [review]
I do not think we need this

**Comment by francopestilli** [comment]
I close this without merging because we have a conflict and we do not need to have one.

**Comment by francopestilli** [comment]
@rosemary-le will make a new pull-request.

**Pull request closed without merging**
